name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - x86
        node:
          - 8
          - 10
          - 12
          - 14
          - 16
        os:
          - macOS-latest
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
        exclude:
          - arch: x86
            os: macOS-latest
          - arch: x86
            os: ubuntu-22.04
          - arch: x86
            os: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm test
      - run:
          echo ::set-output name=job_id::$(node -e
          "console.log(crypto.randomBytes(16).toString('hex'))")
        id: get_job_id
        shell: bash
      - uses: coverallsapp/github-action@v1.1.2
        with:
          flag-name:
            ${{ steps.get_job_id.outputs.job_id }} (Node.js ${{ matrix.node }} -
            $ {{ matrix.arch }} on ${{ matrix.os }})
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
